### ISSUE TITLE
Headers must be stored in an OrderedDict if you wanna emulate a browser

### ISSUE THREAD

**Issue by KOLANICH** [jonluca/Anubis#14]

**Comment by KOLANICH** [comment]
Why have you closed this without any comment?

**Comment by jonluca** [comment]
I thought #15 was going to fix the issue, but you're right, they do need to be an ordered dict.

Would you happen to know what order the headers are supposed to be in?

**Comment by KOLANICH** [comment]
Just launch firefox, enable anti-fingerprinting, relaunch, open the website, open devtools, go to network tab, select any request, toggle the option to show raw headers in the right
