### ISSUE TITLE
I guess the headers for a browser should be defined in a single place

### ISSUE THREAD

**Issue by KOLANICH** [jonluca/Anubis#15]

**Comment by jonluca** [comment]
Yup, I'm actually transitioning to using a randomized modern header from another python library to make it harder to detect Anubis. thanks for the suggestion!

**Comment by KOLANICH** [comment]
Randomized headers are not needed. If you wanna increase entropy use the most widespread set of headers - the ones used by firefox with privacy.resistFingerprinting = true.
