### ISSUE TITLE
feature-request: Snap or flatpak distribution

### ISSUE THREAD

**Issue by jawz101** [jonluca/Anubis#22]
I've never gotten this to install properly.  Has there been any thought into deploying this as a Snap or Flatpak?  I would hope a universal installer would eliminate the particulars of dependency problems and steps involved to set up in a mixed python environment.  I'm one of those casual Linux users that gets lost once steps get too far in the weeds with pip installing things

**Comment by jonluca** [comment]
I'll look into it, but installation should just be a single pip command

`pip3 install anubis-netsec` - does that not work for you?

**Comment by jawz101** [comment]
Plus, every user would simply get whatever changes come and in a standard development environment

**Comment by jonluca** [comment]
Snap complete
