### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by bhavik77** [jonluca/Anubis#24]
Not able to get Shodan result because of the installation error.

Command "/usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t8955aq8/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i5krkv2s-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-t8955aq8/cryptography/

**Comment by jonluca** [comment]
Please look at the Issue guidelines and provide all the information - OS, python version, etc.

Did you install it view `pip install anubis-netsec`? 

Also, I've done all my testing + deployment with Python 3.6.4. Perhaps that's the issue?

**Comment by jonluca** [comment]
Closing due to non response.
