### ISSUE TITLE
error when installing via pip3 segfault

### ISSUE THREAD

**Issue by jawz101** [jonluca/Anubis#25]
* Anubis Version anubis_netsec-0.7.6-py2.py3-none-any.whl
* Python Version 3.6.3
* Full stack trace if crash or installation error
* Machine details (OS, build number, distro, etc.)
ubuntu mate 17.10

@jonluca 
not quite sure how to do a stack trace

pip3 install anubis-netsec
... downloads all the files...
Successfully built censys SSLyze docopt python-nmap shodan tls-parser click-plugins pycparser
Installing collected packages: certifi, urllib3, chardet, idna, requests, netaddr, censys, dnspython, setuptools, nassl, asn1crypto, six, pycparser, cffi, cryptography, tls-parser, SSLyze, docopt, python-nmap, click, click-plugins, colorama, XlsxWriter, shodan, anubis-netsec
Successfully installed SSLyze-1.3.4 XlsxWriter-1.0.2 anubis-netsec-0.7.6 asn1crypto-0.24.0 censys-0.0.8 certifi-2018.1.18 cffi-1.11.4 chardet-3.0.4 click-6.7 click-plugins-1.0.3 colorama-0.3.9 cryptography-2.1.4 dnspython-1.15.0 docopt-0.6.2 idna-2.6 nassl-1.0.3 netaddr-0.7.19 pycparser-2.18 python-nmap-0.6.1 requests-2.18.4 setuptools-38.5.1 shodan-1.7.7 six-1.11.0 tls-parser-1.2.1 urllib3-1.22
Segmentation fault (core dumped)

kern.log
Feb 24 17:02:08  kernel: [  311.672024] random: crng init done
Feb 24 17:02:14  kernel: [  317.955766] pip3[1638]: segfault at a9 ip 0000000000442f24 sp 00007ffda779e648 error 4 in python3.6[400000+3bf000]
Feb 24 17:05:22  kernel: [  505.137210] pip3[1932]: segfault at 22e728 ip 00000000004dc698 sp 00007ffca67b2a00 error 4 in python3.6[400000+3bf000]
Feb 24 17:17:56  kernel: [ 1259.481690] pip3[11814]: segfault at 22e728 ip 00000000004dc698 sp 00007ffe9eed6350 error 4 in python3.6[400000+3bf000]

syslog
Feb 24 17:17:56  kernel: [ 1259.481690] pip3[11814]: segfault at 22e728 ip 00000000004dc698 sp 00007ffe9eed6350 error 4 in python3.6[400000+3bf000]

**Comment by jawz101** [comment]
... unless it's the crash file under /var/logs/_usr_bin_pip3.1000.crash maybe?

**Comment by jawz101** [comment]
maybe it installed using sudo pip3 install anubis-netsec?  I have no idea.  At this point I don't know how to execute the program.  I type anubis in terminal and it has no idea what it is.

**Comment by jonluca** [comment]
Sorry for the late reply. I see that you closed this - did you manage to get it to install properly?

**Comment by jawz101** [comment]
maybe.  I can't quite figure out how to execute it if it's installed.  I think pip3 installs modules/packages to my home directory and then to execute them you run `python3 -m anubis`?  Maybe?  When I do that it says something like a module cannot be run directly or something.

**Comment by jonluca** [comment]
How it should work normally:

You run `pip3 install anubis-netsec`, and it completes normally. Then, anubis should basically just be linked in `/usr/local/bin`. Provided that folder is in your $PATH, you should just be able to call `anubis` from the commandline line.

[See this screenshot for what I mean](https://i.imgur.com/lVUUO32.png)

**Comment by jawz101** [comment]
Thanks.  I'll see if I can try again tonight.
This tool looks cool and I wanted to enumerate subdomains to expand a hostfile I've made for mobile ad/analytic networks. :)
