### ISSUE TITLE
Error installing cryptography (through 'pip3 install -r requirements.txt')

### ISSUE THREAD

**Issue by SweetSoul** [jonluca/Anubis#26]
@jonluca 
Anubis version: none (cloned repo today)
Python version: 'Python 3.6.5rc1'
Machine Details: 
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 02)
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
00:04.0 Signal processing controller: Intel Corporation Skylake Processor Thermal Subsystem (rev 02)
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:15.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #0 (rev 21)
00:15.1 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #1 (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
00:17.0 SATA controller: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] (rev 21)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port (rev f1)
00:1c.4 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #5 (rev f1)
00:1c.5 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #6 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point-LP LPC Controller (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
01:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 940MX] (rev a2)
02:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)

O.S.: Linux parrot 4.16.0-parrot5-amd64 #1 SMP Parrot 4.16.5-1parrot5 (2018-05-03) x86_64 GNU/Linux

Full Stack Trace: 
      https://pastebin.com/gzdyuaVn

Cryptography requirements:

sudo apt-get install build-essential libssl-dev libffi-dev python3-dev
build-essential is already the newest version (12.4).
libffi-dev is already the newest version (3.2.1-8).
libssl-dev is already the newest version (1.1.0h-2).
python3-dev is already the newest version (3.6.4-1).

**Comment by jonluca** [comment]
It looks like you're using an old version of openssl headers. When you run `openssl version` in your terminal what do you get? 

Thanks for the detailed stack trace!

**Comment by SweetSoul** [comment]
openssl version
OpenSSL 1.1.0h  27 Mar 2018

**Comment by SweetSoul** [comment]
openssl version
OpenSSL 1.1.0h  27 Mar 2018

**Comment by jonluca** [comment]
The problem definitely seems to be in the openssl headers you have - ... `build/temp.linux-x86_64-3.6/_openssl.c:911:6: error: conflicting types for ‘BIO_callback_ctrl’`...

It looks like libssl-dev 1.1.0h-2 isn't the official version for Ubuntu 16.04. Try version `1.0.2g-1ubuntu4.12`. 

[It seems like this issue references your same problem](https://github.com/apache/incubator-superset/issues/4870).

**Comment by jonluca** [comment]
@SweetSoul did that fix it?

**Comment by SweetSoul** [comment]
I did not find the 1.0.2g-1ubuntu4.12 version nor install a different version in my pc... I did an `apt --purge remove openssl`, then I used `openssl version` to see if there was something wrong (which were not).

Then i tried the 1.0.2n that i managed to get from the ubuntu repository. 

But when i install, the version that appears to me was ` openssl version
OpenSSL 1.1.0h  27 Mar 2018`

**Comment by SweetSoul** [comment]
I've had some other compatibility problems with parrot, so I decided to move along and changed my distro to linux deepin. I haven't any problems installing in deepin. Feel free to close this issue. Thanks for the help.

**Comment by jonluca** [comment]
There actually was a build issue with crypto due to an outdated dependency. If you have the change/need to try again it should work now. Thanks!
