### ISSUE TITLE
Change "git clone " URL 

### ISSUE THREAD

**Issue by Lucas-L-Alcantara** [jonluca/Anubis#33]
- [ ] set url to  "https://github.com/jonluca/Anubis.git"

Evidence:
" git clone git@github.com:jonluca/Anubis.git
Cloning into 'Anubis'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

**Comment by jonluca** [comment]
I usually prefer to assume that people have set up their public key with their GitHub account. I understand this may not be as common in a security context, so I'll change it. Thanks!
