### ISSUE TITLE
readme.md: typo

### ISSUE THREAD

**Issue by SandMouse** [jonluca/Anubis#4]
In readme.md it reads:

```
API Keys
If you wish to use the --aditional-info flag, you'll need to set up an API key for https://shodan.io.
Copy API_SAMPLE.py to APY.py,
```

You might want to change the last line to:

`Copy API_SAMPLE.py to API.py,`

mind the 'I' instead of the 'Y'.

**Comment by jonluca** [comment]
Fixed, thanks for the report!
