### ISSUE TITLE
SSLyze pinned version does not allow for package installation

### ISSUE THREAD

**Issue by quantshayan** [jonluca/Anubis#49]
# Please follow the general troubleshooting steps first:

- [x] Check you are using Python 3.6
- [x] Make sure you are using pip3 (or any instance of pip associated with Python 3.x)

### Bug reports:

Make sure you include the following:

* Anubis Version
* Python Version
* Full stack trace if crash or installation error
* Machine details (OS, build number, distro, etc.)

Also, please assign @jonluca to all issues at first.

Please replace this line with a brief summary of your issue.

### Features:

**Please note by far the quickest way to get a new feature is to make a Pull Request.**

Otherwise, open an issue and tag it with "feature-request"

**Comment by quantshayan** [comment]
The nassl version is causing error while running ($pip3 install . ). 

The same issue does comeup while installing requirements.txt but i have manually changed the version number, but in the in the final installation command this fails. 


This is my error traceback message.
------------------------------------------------------------------------------- 
Could not find a version that satisfies the requirement nassl<2.2.0,>=2.1.0 (from sslyze==2.0.3->anubis-netsec==0.9.5) (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3, 3.0.0)
ERROR: No matching distribution found for nassl<2.2.0,>=2.1.0 (from sslyze==2.0.3->anubis-netsec==0.9.5)

------------------------------------

Thanks in the Advance !!

**Comment by jonluca** [comment]
Thanks, will take a look sometime in the next few days!

**Comment by jonluca** [comment]
Fixed in v0.9.7
