### ISSUE TITLE
readme.md: typo

### ISSUE THREAD

**Issue by SandMouse** [jonluca/Anubis#5]
readme.md reads:

`pip install -r requirements`

While the filename is requirements.txt

Suggestion: since Anubis is running using Python 3.6 and I'm running both Python2 and Python3, I had to specify `pip3` in order to get the requirements installed. (macos 10.13.2)

**Comment by zoutepopcorn** [comment]
Thanks for the great repo. I dont want errors on my system.

I got it now working in a docker: 
``` 
FROM python:latest
MAINTAINER nobody
RUN apt-get update
WORKDIR /home
RUN git clone https://github.com/jonluca/Anubis
WORKDIR /home/Anubis 
RUN pip install -r requirements.txt
RUN pip install -e .[test]
RUN echo "echo 'https://github.com/jonluca/Anubis\n\nanubis -t reddit.com'" >> /root/.bashrc
CMD ["/bin/bash"]
```

or
docker pull zoutepopcorn/anubis

**Comment by jonluca** [comment]
Yeah I've got a few installation bugs I need to clean up. Thanks for the report!
