### ISSUE TITLE
Issue with installation SSLyze version from requirements file.

### ISSUE THREAD

**Issue by jffin** [jonluca/Anubis#53]
# Please follow the general troubleshooting steps first:

- [x] Check you are using Python 3.6
- [x] Make sure you are using pip3 (or any instance of pip associated with Python 3.x)

### Bug reports:

Make sure you include the following:

* Anubis Version 
* Python Version
* Full stack trace if crash or installation error
* Machine details (OS, build number, distro, etc.)

Also, please assign @jonluca to all issues at first.

Please replace this line with a brief summary of your issue.

### Features:

**Please note by far the quickest way to get a new feature is to make a Pull Request.**

Otherwise, open an issue and tag it with "feature-request"

==============================================================

I'm trying to install into docker alpine image.
I tried python versions 3.6.12, 3.7.9, 3.8.5

installation command tried ```python -m pip install --no-cache-dir anubis-netsec```
also tried to build from source with ```pip3 install .```
 

```ERROR: Could not find a version that satisfies the requirement sslyze==3.0.7 (from anubis-netsec) (from versions: 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, ERROR: No matching distribution found for sslyze==3.0.7 (from anubis-netsec)```

**Comment by jffin** [comment]
also tried install on ```python:3.6-slim-jessie``` with same result 

``` ERROR: Could not find a version that satisfies the requirement sslyze==3.0.7 (from anubis-netsec) (from versions: 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.14.0, 0.14.1, 0.14.2, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.4, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4)```

**Comment by jffin** [comment]
Is there any other way to install the library?

**Comment by jonluca** [comment]
Looks like this is an issue with python 3.8 - sslyze requires nassl>= 3.1.0, and nassl doesn't support python3.8.

I've actually had a ton of issues with that library and versioning. I'm just going to rip it out of the next version. It'll be released later today, v0.9.9.

**Comment by jonluca** [comment]
Fixed in https://pypi.org/project/anubis-netsec/0.9.9/, let me know if this works.
