### ISSUE TITLE
How to get only subdomains?

### ISSUE THREAD

**Issue by slavaGanzin** [jonluca/Anubis#62]
Hello

Currently, there is no way to get only subdomains and not logo and debug messages.
So add --silent or just pipe debug to stderr, so you can do ’anubis -t substack.com 2>/dev/null’

**Comment by jonluca** [comment]
Added the `-S` or `--silent` flag in release v1.0, 882bedc4e234459d87b24a808ec3097106cf8ea7

**Comment by slavaGanzin** [comment]
@jonluca Awesome. Thanks

**Comment by slavaGanzin** [comment]
@jonluca You forgot to add '\n' here:
https://github.com/jonluca/Anubis/commit/882bedc4e234459d87b24a808ec3097106cf8ea7#diff-bae22825fafd2ad8220fb964fbeebf79c895c3c92010cfc13c90fec255efbddaR121

```
$ anubis -t substack.com --silent  | head -c 100
cnc.substack.comenough.substack.commuthukrishnalab.substack.comcubannomad.substack.comhardware.subst⏎  
```

Like here:
https://github.com/jonluca/Anubis/commit/882bedc4e234459d87b24a808ec3097106cf8ea7#diff-bae22825fafd2ad8220fb964fbeebf79c895c3c92010cfc13c90fec255efbddaR141
````
$ anubis -t substack.com --silent --ip | head
messari.substack.com
proofoftake.substack.com
99d.substack.com
sinocism.substack.com
mg-202-14.substack.com
refactoring.substack.com
cronicasdotitanic.substack.com
email.mg-pr.substack.com
jobstobedone.substack.com
heyreprotech.substack.com
```

**Comment by jonluca** [comment]
Thanks for the PR and fix. This has been released.
