### ISSUE TITLE
Adding Spyse as a data source [Feature-Request]

### ISSUE THREAD

**Issue by Luci-d** [jonluca/Anubis#68]
### Features:

**Please note by far the quickest way to get a new feature is to make a Pull Request.**

Otherwise, open an issue and tag it with "feature-request"

### The solution
We are suggesting you add Spyse as one of the data sources for: DNS, subdomain enumeration, retrieving web information, hosts, certificates, and ports.
Potential is immense. Contact us if you need any help or a free subscription to make it free for users.

### Possible alternatives
Alternatives could be shodan or censys.

### Additional context
I'm offering Spyse because it has different scanning and analyzing systems that provide a more clear and sometimes larger amounts of data.

Notice: I work for Spyse.

**Comment by jonluca** [comment]
I've added it for subdomain enumeration. It does require an API key, though. so not sure about the level of adoption it'll get.
