### ISSUE TITLE
Result contains `*` character

### ISSUE THREAD

**Issue by shelld3v** [jonluca/Anubis#74]
# Please follow the general troubleshooting steps first:

- [x] Check you are using Python 3.6
- [x] Make sure you are using pip3 (or any instance of pip associated with Python 3.x)

### Bug reports:

Some subdomains in the result contain `*.`:

```
vpn.awscorp.uberinternal.com
corpmdm.uberinternal.com
*.uberinternal.com
vpn-china-szx1.uberinternal.com
--- snippet ---
jira-cdn-staging.uberinternal.com
*.tm1ext.awscorp.uberinternal.com
uberhubtest.uberinternal.com
gw08-usw1.awscorp.uberinternal.com
--- snippet ---
lsfosq_us1.uberinternal.com
*.it-tools.uberinternal.com
gw08-sae1.awscorp.uberinternal.com
```

**Comment by jonluca** [comment]
Do we not want this? Because sometimes the `*` character is on a subdomain itself. I think I'll keep it as is for now, unless someone has a compelling reason to not include them

**Comment by shelld3v** [comment]
Can you explain "sometimes the `*` character is on a subdomain itself"? I might get you wrong but domain names can only use the letters a to z, the numbers 0 to 9, and the hyphen (-) character

**Comment by jonluca** [comment]
Yes, it's not a valid subdomain itself, but the results will sometimes be valid subdomains with the prefix.

For instance, if you do a search for `google.com`, a result might be `*.mail.google.com`, which is interesting. It either means that a wildcard certificate was issued for that subdomain, or that one of the providers lists it like that.
