### ISSUE TITLE
error when launch anubis

### ISSUE THREAD

**Issue by ztencmcp** [jonluca/Anubis#8]
#OS: MacOS 10.12.6
#Python: 2.7.14
Error like this:
-----------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/anubis", line 11, in <module>
    load_entry_point('Anubis', 'console_scripts', 'anubis')()
  File "/opt/information-gathering/subdomains/Anubis/anubis/cli.py", line 73, in main
    import anubis.commands
  File "/opt/information-gathering/subdomains/Anubis/anubis/commands/__init__.py", line 1, in <module>
    from .target import *
  File "/opt/information-gathering/subdomains/Anubis/anubis/commands/target.py", line 9, in <module>
    from urllib.parse import urlsplit
ImportError: No module named parse
---------------------------------------------------------------------------------------------
Anubis (0.1.0, /opt/information-gathering/subdomains/Anubis)
asn1crypto (0.23.0)
attrs (17.3.0)
backports-abc (0.5)
censys (0.0.8)
certifi (2017.11.5)
cffi (1.11.2)
chardet (3.0.4)
click (6.7)
click-plugins (1.0.3)
colorama (0.3.9)
configparser (3.5.0)
coverage (4.4.2)
cryptography (1.9)
Django (1.11.7)
dnspython (1.15.0)
docopt (0.6.2)
enum34 (1.1.6)
funcsigs (1.0.2)
gevent (1.2.2)
greenlet (0.4.12)
idna (2.6)
ipaddress (1.0.18)
lxml (4.1.1)
nassl (1.0.1)
netaddr (0.7.19)
parse (1.8.2)
pdfkit (0.6.1)
pip (9.0.1)
pluggy (0.6.0)
py (1.5.2)
pyasn1 (0.4.2)
pycparser (2.18)
pyOpenSSL (17.5.0)
pytest (3.3.1)
pytest-cov (2.5.1)
python-nmap (0.6.1)
pytz (2017.3)
requests (2.10.0)
rsa (3.4.2)
setuptools (36.5.0)
shodan (1.7.7)
singledispatch (3.4.0.3)
six (1.11.0)
SSLyze (1.2.0)
tls-parser (1.1.1)
tornado (4.5.2)
typing (3.6.2)
urllib3 (1.22)
wheel (0.30.0)
XlsxWriter (1.0.2)

**Comment by jonluca** [comment]
Anubis requires python 3.6. Sorry!
