### ISSUE TITLE
E: Package 'python-dev' has no installation candidate

### ISSUE THREAD

**Issue by ryhankabir562** [jonluca/Anubis#80]
┌──(kali㉿Kali)-[~/Anubis]
└─$ sudo apt-get install python3-pip python-dev libssl-dev libffi-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python2-dev python2 python-dev-is-python3

E: Package 'python-dev' has no installation candidate

**Comment by jonluca** [comment]
Looks like there might be something wrong with your sources list for `apt`? It might work without it though, just try installing `pip3 install anubis-netsec` and see if it works.
